# Generated by Django 4.0.1 on 2023-03-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
    ]
