# Generated by Django 4.0.1 on 2023-03-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='productattributepictures',
            options={'verbose_name_plural': 'Product Attribute Pictures'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name_plural': 'Product Tags'},
        ),
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name_plural': 'Address Book'},
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('processing', 'In Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=150),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.CharField(max_length=1000),
        ),
    ]
