# Generated by Django 4.0.1 on 2023-03-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cart_options_alter_countries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='color',
            field=models.CharField(default='blue', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='size',
            field=models.CharField(default='Medium', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('recieved', 'Recieved'), ('processing', 'In Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='recieved', max_length=150),
        ),
    ]
