# Generated by Django 4.0.1 on 2023-03-27 11:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_cartorderitems_color_cartorderitems_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Privacy and Policy',
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Return Policy',
            },
        ),
    ]
