# Generated by Django 4.0.1 on 2023-04-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_privacypolicy_returnpolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': '- Countries'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': '- Privacy and Policy'},
        ),
        migrations.AlterModelOptions(
            name='returnpolicy',
            options={'verbose_name_plural': '- Return Policy'},
        ),
    ]
